repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: elastic
    url: https://helm.elastic.co

releases:
  - name: my-postgresql
    chart: bitnami/postgresql
    namespace: logging
    values:
      - postgresql-values.yaml  # Make sure to create this values file

  - name: hello-world-python
    chart: ./hello-world-python
    namespace: default
