apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 10Gi  # Specify the desired size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql  # Adjust this path based on your environment
