apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default  # Adjust if using a different namespace
spec:
  serviceName: "postgres"
  replicas: 3  # Number of PostgreSQL instances
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13  # Use the version you require
        env:
        - name: POSTGRES_USER
          value: myuser        # Change as needed
        - name: POSTGRES_PASSWORD
          value: mypassword    # Change as needed
        - name: POSTGRES_DB
          value: mydatabase    # Change as needed
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi  # Adjust based on your needs
