apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: sharanu363/hello-world-python1:latest
        resources:
          requests:
            cpu: "300m"
            memory: "1Gi"
          limits:
            cpu: "600m"
            memory: "2Gi"
        ports:
        - containerPort: 5044
