apiVersion: v1
kind: Service
metadata:
  name: hello-world-python
spec:
  type: NodePort  # Change this to NodePort if you're running locally
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: hello-world-python
